apiVersion: v1
kind: Service
metadata:
  name: dizzy
  labels:
    app: dizzy
    tier: frontend
spec:
  sessionAffinity: ClientIP
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000 # Could be omiitted as it is inherits from "port" above. Left for brevity.
    nodePort: 30001
  selector:
    app: dizzy
    tier: frontend
