apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379 # Could be omiitted as it is inherits from "port" above. Left for brevity.
  selector:
    app: redis
    role: master
    tier: backend
